languageCode:           "es"
title:                  "Sistema de diseño"
baseURL:                "http://ux.gluo.mx/ux/projects/gluo-sdd/documentacion/"
enableInlineShortcodes: true

pygmentsUseClasses:     true
pygmentsCodeFences:     true

buildDrafts:            true
buildFuture:            true

metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "dist"

module:
  mounts:
    - source:           site/content
      target:           content
    - source:           site/assets
      target:           assets
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static


params:
  description:          "Compilado de tecnologías front-end basadas en bootstrap."
  authors:              "GLUO"